version: '3.7'
services: 
  db:
    image: mysql:5.7.30
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qlbh
    volumes: 
      - ./home/irvine/db/qlbh:/var/lib/mysql

  app:
    build: .
    ports:
      - 3000:3000
    depends_on: 
      - db
    volumes: 
      - .:/usr/qlbh-app
      - /usr/qlbh-app/node_modules
